import math
#Sun's Mass in kilograms
m1=1.989E30
#Neptune's Mass in kilograms
m2=1.024E26
#Distance between the Sun and Neptune in kilometers
r=4.4766E9
#mass ratio (mu2)
mu2=m2/(m1+m2)
print(50*"-")
print("Mü2 değeri: ",mu2)
XL1=r*(1-pow((mu2/3),(1/3)))
XL2=r*(1+pow((mu2/3),(1/3)))
XL3=-r*(1+(5*mu2/12))
XL4and5=(r/2)*((m1-m2)/(m1+m2)) 
YL4=(math.sqrt(3)/2)*r
YL5=-YL4
print(50*"-")
print("1. Lagrange Noktası")
print("x ekseni: ",XL1, "km")
print("y ekseni: 0 km")
print("r=1 birim olmak üzere eksen değerleri")
print(50*"*")
print("Birimsel x ekseni: ", XL1/r, "birim")
print("Birimsel y ekseni: ", 0/r, "birim")
print(50*"-")
print("2. Lagrange Noktası")
print("x ekseni: ",XL2, "km")
print("y ekseni: 0 km")
print("r=1 birim olmak üzere eksen değerleri")
print(50*"*")
print("Birimsel x ekseni: ", XL2/r, "birim")
print("Birimsel y ekseni: ", 0/r, "birim")
print(50*"-")
print("3. Lagrange Noktası")
print("x ekseni: ",XL3, "km")
print("y ekseni: 0 km")
print("r=1 birim olmak üzere eksen değerleri")
print(50*"*")
print("Birimsel x ekseni: ", XL3/r, "birim")
print("Birimsel y ekseni: ", 0/r, "birim")
print(50*"-")
print("4. Lagrange Noktası")
print("x ekseni: ",XL4and5, "km")
print("y ekseni: ", YL4, "km")
print("r=1 birim olmak üzere eksen değerleri")
print(50*"*")
print("Birimsel x ekseni: ", XL4and5/r, "birim")
print("Birimsel y ekseni: ", YL4/r, "birim")
print(50*"-")
print("5. Lagrange Noktası")
print("x ekseni: ",XL4and5, "km")
print("y ekseni: ", YL5, "km")
print("r=1 birim olmak üzere eksen değerleri")
print(50*"*")
print("Birimsel x ekseni: ", XL4and5/r, "birim")
print("Birimsel y ekseni: ", YL5/r, "birim")
print(50*"-")